export const COUNTRY_CODES = [
	{ name: "Bolivia", dialCode: "+591", flag: "🇧🇴" },
	{ name: "Argentina", dialCode: "+54", flag: "🇦🇷" },
	{ name: "Brasil", dialCode: "+55", flag: "🇧🇷" },
	{ name: "Chile", dialCode: "+56", flag: "🇨🇱" },
	{ name: "Colombia", dialCode: "+57", flag: "🇨🇴" },
	{ name: "Ecuador", dialCode: "+593", flag: "🇪🇨" },
	{ name: "Paraguay", dialCode: "+595", flag: "🇵🇾" },
	{ name: "Peru", dialCode: "+51", flag: "🇵🇪" },
	{ name: "Uruguay", dialCode: "+598", flag: "🇺🇾" },
	{ name: "Venezuela", dialCode: "+58", flag: "🇻🇪" },
	{ name: "Mexico", dialCode: "+52", flag: "🇲🇽" },
	{ name: "Estados Unidos", dialCode: "+1", flag: "🇺🇸" },
	{ name: "España", dialCode: "+34", flag: "🇪🇸" },
	{ name: "Panama", dialCode: "+507", flag: "🇵🇦" },
	{ name: "Costa Rica", dialCode: "+506", flag: "🇨🇷" },
	{ name: "Guatemala", dialCode: "+502", flag: "🇬🇹" },
	{ name: "Republica Dominicana", dialCode: "+1", flag: "🇩🇴" },
	{ name: "Cuba", dialCode: "+53", flag: "🇨🇺" },
	{ name: "Italia", dialCode: "+39", flag: "🇮🇹" },
	{ name: "Francia", dialCode: "+33", flag: "🇫🇷" },
];
